version: "3.3"
services:
  jenkins:
    image: jenkins
    build: .
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: volume
        source: jenkins
        target: /var/jenkins_home
volumes:
  jenkins:
